### ISSUE TITLE
Change binding example

### ISSUE THREAD

**Issue by theldoria** [diadochos/org-babel-eval-in-repl#14]
I suggest changing the key binding example to something like the following:

``` emacs-lisp
  (defun org-meta-return-around (org-fun &rest args)
    "Run `ober-eval-in-repl' if in source code block or example block and `org-meta-return' otherwise."
    (if (org-in-block-p '("src" "example"))
        (ober-eval-in-repl)
      (apply org-fun args)))
  (advice-add 'org-meta-return :around #'org-meta-return-around)

  (defun org-ctrl-return-around (org-fun &rest args)
    "Run `ober-eval-block-in-repl' if in source code block and `org-insert-heading-respect-content' otherwise."
    (if (org-in-block-p '("src" "example"))
        (ober-eval-block-in-repl)
      (apply org-fun args)))
  (advice-add 'org-insert-heading-respect-content :around #'org-ctrl-return-around)
```

That's what I use.
:exclamation: Note, however, that I switched `C-return` to `M-return` and `C-c C-c` to `C-return`!
Reason for that is:

- I use `M-return` for `eval-in-repl` because `C-return` is used by `cua-mode`
- I still want `C-c C-c` to function as usual in `org-mode`

:point_right: The suggested solution in your `README.md` could probably be to

- [ ] switch `C-return` and `M-return` from my example
- [ ] or `org-ctrl-c-ctrl-c` could be adviced and `ober-eval-block-in-repl`be bound to `C-u C-c C-c`.

:point_right: Furthermore readily made around functions could be provided.

**Comment by diadochos** [comment]
Nice suggestion!
I have decided to do the following (it's already at master):
- Write both the simple usage (to demonstrate) and your around-advice style.
- `C-<return>` for `ober-eval-in-repl`, and `M-<return>` for `ober-eval-block-in-repl`
- No readily made around functions are provided (for brevity)
- `org-ctrl-c-ctrl-c` could have been advised, but I didn't for now (because I wanted to quickly just fix this)

**Comment by diadochos** [comment]
Closing now.
