### ISSUE TITLE
How to add results to org buffer

### ISSUE THREAD

**Issue by karthink** [diadochos/org-babel-eval-in-repl#30]
Is there a way to use `org-babel-eval-in-repl` while also appending the result after the code block the way org-babel usually does? I read through the description and the wiki but couldn't find anything besides this:

> Output is reproducible as long as the code is saved

I have trouble understanding what this means.

(EDIT: I understand that what I'm asking can be simulated using org's built in code block evaluation + the `:session` keyword, but I can't get async execution that way, and I can't use it with MATLAB.)

**Comment by diadochos** [comment]
Hi karthink, thanks for inquiring.

For that purpose, I can recommend you this package:
https://github.com/astahlman/ob-async

I’m not certain if that package had MATLAB support, but please check their repository.

NB: There must have been a reason why I had to write this package instead of just using theirs, but I cannot recall why.

> Output is reproducible as long as the code is saved

This is intended to mean that the same results can be observed by running the codes again (unless the result is random).

**Comment by diadochos** [comment]
Let me close this issue for now. Feel free to reopen it if there are further questions.
